[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
framework = arduino

build_flags = 
    -DTEMP_SENSOR_I2C_ADDR=0x48
    -DI2C1_SCL=PB6
    -DI2C1_SDA=PB7

lib_deps = 
    Wire
    ArduinoJson
